/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;

/**
 *
 * @author garmin
 */
public class menuScreen extends javax.swing.JFrame {
    
    public int sessionID;
    public int prim;

    /**
     * Creates new form menu
     */
    public menuScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        posButton = new javax.swing.JButton();
        productsButton = new javax.swing.JButton();
        ordersButton = new javax.swing.JButton();
        clockButton = new javax.swing.JButton();
        salesButton = new javax.swing.JButton();
        adminButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        posButton.setText("POS");
        posButton.setMaximumSize(new java.awt.Dimension(200, 100));
        posButton.setMinimumSize(new java.awt.Dimension(200, 100));
        posButton.setPreferredSize(new java.awt.Dimension(200, 100));
        posButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posButtonActionPerformed(evt);
            }
        });

        productsButton.setText("Products");
        productsButton.setMaximumSize(new java.awt.Dimension(200, 100));
        productsButton.setMinimumSize(new java.awt.Dimension(200, 100));
        productsButton.setPreferredSize(new java.awt.Dimension(200, 100));
        productsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsButtonActionPerformed(evt);
            }
        });

        ordersButton.setText("Orders");
        ordersButton.setMaximumSize(new java.awt.Dimension(200, 100));
        ordersButton.setMinimumSize(new java.awt.Dimension(200, 100));
        ordersButton.setPreferredSize(new java.awt.Dimension(200, 100));
        ordersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersButtonActionPerformed(evt);
            }
        });

        clockButton.setText("Clock IN/OUT");
        clockButton.setMaximumSize(new java.awt.Dimension(200, 100));
        clockButton.setMinimumSize(new java.awt.Dimension(200, 100));
        clockButton.setPreferredSize(new java.awt.Dimension(200, 100));
        clockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockButtonActionPerformed(evt);
            }
        });

        salesButton.setText("Sales Analytics/Reports");
        salesButton.setMaximumSize(new java.awt.Dimension(200, 100));
        salesButton.setMinimumSize(new java.awt.Dimension(200, 100));
        salesButton.setPreferredSize(new java.awt.Dimension(200, 100));
        salesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesButtonActionPerformed(evt);
            }
        });

        adminButton.setText("Admin");
        adminButton.setMaximumSize(new java.awt.Dimension(200, 100));
        adminButton.setMinimumSize(new java.awt.Dimension(200, 100));
        adminButton.setPreferredSize(new java.awt.Dimension(200, 100));
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(productsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(posButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(clockButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ordersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ordersButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clockButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void posButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posButtonActionPerformed
        // TODO add your handling code here:
        boolean valid = classes.userSessions.isSessionValid(sessionID);
        System.out.println(sessionID);
        if (valid == false){
            JOptionPane.showMessageDialog(null, "You have been timed out, please log back in.");
            loginScreen login = new loginScreen();
            login.setDefaultCloseOperation(loginScreen.EXIT_ON_CLOSE);
            login.pack();
            login.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_posButtonActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        // TODO add your handling code here:
        boolean valid = classes.userSessions.isSessionValid(sessionID);
        System.out.println(sessionID);
        if (valid == false){
            JOptionPane.showMessageDialog(null, "You have been timed out, please log back in.");
            loginScreen login = new loginScreen();
            login.setDefaultCloseOperation(loginScreen.EXIT_ON_CLOSE);
            login.pack();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_adminButtonActionPerformed

    private void ordersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersButtonActionPerformed
        // TODO add your handling code here:
        boolean valid = classes.userSessions.isSessionValid(sessionID);
        System.out.println(sessionID);
        if (valid == false){
            JOptionPane.showMessageDialog(null, "You have been timed out, please log back in.");
            loginScreen login = new loginScreen();
            login.setDefaultCloseOperation(loginScreen.EXIT_ON_CLOSE);
            login.pack();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_ordersButtonActionPerformed

    private void productsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsButtonActionPerformed
        // TODO add your handling code here:
        boolean valid = classes.userSessions.isSessionValid(sessionID);
        System.out.println(sessionID);
        if (valid == false){
            JOptionPane.showMessageDialog(null, "You have been timed out, please log back in.");
            loginScreen login = new loginScreen();
            login.setDefaultCloseOperation(loginScreen.EXIT_ON_CLOSE);
            login.pack();
            login.setVisible(true);
            this.dispose();
        }
        productScreen screen = new productScreen();
        screen.setDefaultCloseOperation(productScreen.DISPOSE_ON_CLOSE);
        screen.pack();
        screen.setVisible(true);
        screen.primaryKey = prim;

        
    }//GEN-LAST:event_productsButtonActionPerformed

    private void salesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesButtonActionPerformed
        // TODO add your handling code here:
        boolean valid = classes.userSessions.isSessionValid(sessionID);
        System.out.println(sessionID);
        if (valid == false){
            JOptionPane.showMessageDialog(null, "You have been timed out, please log back in.");
            loginScreen login = new loginScreen();
            login.setDefaultCloseOperation(loginScreen.EXIT_ON_CLOSE);
            login.pack();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_salesButtonActionPerformed

    private void clockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockButtonActionPerformed
        // TODO add your handling code here:
        boolean valid = classes.userSessions.isSessionValid(sessionID);
        System.out.println(sessionID);
        if (valid == false){
            JOptionPane.showMessageDialog(null, "You have been timed out, please log back in.");
            loginScreen login = new loginScreen();
            login.setDefaultCloseOperation(loginScreen.EXIT_ON_CLOSE);
            login.pack();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_clockButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JButton clockButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ordersButton;
    private javax.swing.JButton posButton;
    private javax.swing.JButton productsButton;
    private javax.swing.JButton salesButton;
    // End of variables declaration//GEN-END:variables
}
